### ISSUE TITLE
Update to WebdriverIO v8

### ISSUE THREAD

**Issue by christian-bromann** [amiya-pattnaik/webdriverIO-with-cucumberBDD#27]
Hey 👋 

Thanks for providing this boilerplate project. It seems like it uses WebdriverIO v6 or older which are versions that the WebdriverIO team has deprecated. Please update the dependencies as we otherwise have to remove it [from our docs](https://webdriver.io/docs/boilerplates).

Let me know if you have any questions! Thank you!

**Comment by amiya-pattnaik** [comment]
Hi Chris,I am sorry... I completely forgot it. Please allow me one week of time I will update the repos and will raise a pull requests. Thanks for your support.
Regards,Amiya 

    On Friday, 7 October 2022, 01:17:46 AM GMT-5, Christian Bromann ***@***.***> wrote:  
 
 


Hey 👋
 
Thanks for providing this boilerplate project. It seems like it uses WebdriverIO v6 or older which are versions that the WebdriverIO team has deprecated. Please update the dependencies as we otherwise have to remove it from our docs.

Let me know if you have any questions! Thank you!

**Comment by amiya-pattnaik** [comment]
Hi Chris,
The boilerplate repo is updated to V8. Please check and let me know.
