### ISSUE TITLE
Unexpected token import - Need help urgently

### ISSUE THREAD

**Issue by PavanGurramQA** [amiya-pattnaik/webdriverIO-with-cucumberBDD#4]
Hi Amiya,

I created page objects exactly like yours but when I run gulp test, it is failing with below error:
![importerror](https://user-images.githubusercontent.com/36418052/36110792-d7611236-101b-11e8-9398-d101e019dc05.jpg)

Unexpected token import
import Page from './page';
^^^^^^

I have also added bable dependencies from your package.json. Please can you help me as I got stuck now?? Appreciate your quick response.

**Comment by amiya-pattnaik** [comment]
Hi Pavan
The example show is using `Grunt`. Either you can run it from grunt or through npm script command. I have not used gulp, but i think the error `Unexpected token import` you are getting because of the not having .babelrc file in the same location where package.json reside. If you download the my repo then you should not get the `Unexpected token import` error as in the package.json it has the information about the babel complier. You can either add the .babelrc file or you can mention in the package.json.

**Comment by PavanGurramQA** [comment]
Hi Amiya,

Hope you are doing good.

Many thanks for your response. I will try your suggestion and let you know the outcome. Im in critical situation and may need your help going forward if the issue is not resolved so request you to help me.

**Comment by PavanGurramQA** [comment]
Hi Amiya,

The issue now is resolved by placing barbel file and with right commands in it. However, the URL (which we want to load eg: google.co.uk) is not getting loaded on the browser. I have followed exact page objects and code style like your's. Am i missing anything else to include? Attached are the js files for Page, GooglePage (page object) and also step def file is included. Images of browser instance (where URL is not loaded) and cmd prompt (with no errors stating test passed) are also attached. Please help. Many thanks in advance.

**Comment by amiya-pattnaik** [comment]
Hi Pavan,
I think you re using your own framework and I am not sure how and where the calls are being made. Also i saw your page class, your selector's are not proper. Hence not able to help much. But looking 
 at the snap shot, it seems your chrome browser version is  not compatible with selenium version and is the reason no action is being performed on the browser. 

Please follow my my sample project and you should be able to proceed. The issues which you are getting is nothing do with this project repos. hence closing this.
