### ISSUE TITLE
not able to run scneario with tag name in feature file

### ISSUE THREAD

**Issue by amoleb6** [amiya-pattnaik/webdriverIO-with-cucumberBDD#5]
I have a requirement to run the specific scenarios from feature file. I have tried with 
--cucumberOpts.tagExpression=@sceanrio1,@scenario2.  but when i execute this all the scenarios from the feature file ran..  how i can run the specific scenarios from the file??  I am executing it with gulp task..Thanks

**Comment by amiya-pattnaik** [comment]
you have mentioned - --cucumberOpts.tagExpression=@sceanrio1,@scenario2
want to know which file you have mentioned  @tag ???

**Comment by amiya-pattnaik** [comment]
hope above answer helped you.

**Comment by mandy8055** [comment]
Hello Sir,
I am using your boilerplate project for my reference and learning. Sir I want to know how can we pass the tag names(in the case of more than one feature) in command line argument; something like`npm run test --tags=@Any_Feature_tag` so that I could change the tags argument dynamically according to user's wish.

**Comment by amiya-pattnaik** [comment]
hi Mandy,
pls refer to my earlier comment above on on Mar 7.

**Comment by sankalp-gupta** [comment]
Hello Amiya,

Hope you are doing good, like Mandy, I am also facing same problem, I can handle tags from configuration file but how to do it run-time, it's not working when I am passing it from command line.
